// GENERATED by tools/trace_map.py from GVSU's Allendale campus map, then
// safe to edit by hand: change a character in `rows` to change that tile.
//
// Tile legend:
//   .  grass                  B  building (shapes come from connected B tiles)
//   R  road                   W  sidewalk             D  dirt trail
//   r b y g u o k  parking lots, by permit color (red, blue, yellow, green,
//                  purple, orange, black)
//   F  field / turf           ~  water                =  bridge
//   G  golf course            A  farmland             K  Cook Carillon Tower
//   T  woods (dense trees)    t  arboretum (trees)    V  ravine (impassable)
//
// Rerunning the tracer overwrites hand edits, so keep a copy of anything you
// change, or make the change in the tracer instead.
window.LQ = window.LQ || {};

LQ.CAMPUS_MAP = {
  width: 214,
  height: 283,
  // Map image pixels per tile, and the image pixel at tile (0, 0).
  scale: 2,
  origin: [145, 46],
  // Top-left tile of the 2x2 Cook Carillon Tower.
  carillon: [115, 142],

  // One string per row of tiles, north to south. Row numbers are in the comments.
  rows: [
    '............................RR............RRR........................................................................................RRR............................................................TTTTTTTTTTT~~~~~~T', // 0
    '............................RR.BB.........RRR........................................................................................RRR............................................................TTTTTTTTTTT~~~~~~T', // 1
    '............................RRBBB.........RRR........................................................................................RRR............................................................TTTTTTTTTTT~~~~~~T', // 2
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.B.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.RRRRRRRRRRRRRR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 3
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.R.R.RR.RRRR.RRRRR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 4
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.R....R.R.R.BBBBB.R.BBBB.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 5
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.RRRRRRR........RRRRRR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 6
    '..RR.......R.R.....WWWW........................................WWWWWWWWWWWWRR.....RR...............WWWWWWWWW.RR....RR....................WWWWWWWWWWW...RR...........................................TTTTTTTTTTT~~~~~~T', // 7
    'RRRRRRRRRRRRRRRRRRRR..RRRR...........RR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 8
    'RRRRRRRRRRRRRRRRR.BBBRR.BBBBB...BBBBB.R.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 9
    'RRRRRRRRRRRRRRRRR.RBBRRR.R..RR.RBBRRR.R.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 10
    'RRRRRRRRRRRRRRRR.RRRRRRRRRRRRR.RRRR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR', // 11
    '..................................................................................RRR...............................................................................................................TTTTTTTTTTT~~~~~~T', // 12
    '..................................................................................RRR...............................................................................................................TTTTTTTTTTT~~~~~~T', // 13
    '..................................................................................RRR..........................F....................................................................................TTTTTTTTTTT~~~~~~T', // 14
    '..................................................................................RRR.......................gggggF..................................................................................TTTTTTTTTTT~~~~~~T', // 15
    '..................................................................................RRR......................Fgggggg..................................................................................TTTTTTTTTTT~~~~~~T', // 16
    '..................................................................................RRRW.....................Fgggggg...bbbbbbbb....................................................F...FF.............TTTTTTTTTTT~~~~~~T', // 17
    '..................................................................................RRRW.....................Fgggggg...bbbbbbbbbbbbbbbbbbb..RRR...........................yyyyyyyyyyyyyyy.............TTTTTTTTTTT~~~~~~T', // 18
    '...................................................................................RRW.....................Fgggggg...bbbbbbbbbbbbbbbbbbb..RRR......................yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 19
    '...................................................................................RRW.....................Fgggggg...bbbbbbbbbbbbbbbbbb.....R..............R.....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 20
    '...................................................................................RRR......................gggggF...bbbbbbbbbbbb......BBBB.R.............RRR..yyyyyyyyyyyyyyyyyyyy.yyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 21
    '...................................................................................RRR......................FFFFF..W...................BBBBB.............RRR..yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 22
    '....................................................................................RR.......................RRWWWWW.......bbbbb...........B...........RRRRR.yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 23
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........................................RRR............BB........R.............bbbbb...........B..........RRR..R..yyyyyyyyyyyyyyyy..yyy.yyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 24
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........................................RRR.........BBBBB........R.............bbbbb........BBBB.....W....RR......yyyyyyyyyyyyyy.yyyyyy.yyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 25
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG............................................RRRW.......BBBBBBB.F....R.............bbbb..................WWR...........yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 26
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.............................................RRWW......BBBBBBBggFRRRR..FF........BBBBBB.................W.R............yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 27
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.............................................RRRW.....RR.BBBBBggF..RRRFggF.BBBBBBBBBBBB.R.................R........y....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 28
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG....................................................RRRRR....FgFF..RR.FgggFBBBBBBBBBBBBRR.................RR.....yyyy....yyyy..................yyyyyyyyyyyyTTTTTTTTTTT~~~~~~T', // 29
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..................................................RRR.......WFgF...RR.Fggg.BBBBBBBBBBBBRR.................RR...yyyyyyy...yyy.....yyyyy.....................TTTTTTTTTTT~~~~~~T', // 30
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..................................................RRW.......WWW....R..Fggg.BBBBBBBBBBBBRR..................R..yyyyyyyyy........yyyyyyyyyyyyyyyy............TTTTTTTTTTT~~~~~~T', // 31
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........BBBB..................................BBBWW......RRW....R..FgggFBBBBBBBBBRRRRR..................R..yy.yy.yyy........yyyyyyyyyyyyyyyyy.......FF..TTTTTTTTTTT~~~~~~T', // 32
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....BBBB.BB.......................................BBWW.....R.....RR..FgggF...BBBBB.RRRR.............Fyyyy.RR.yy.yy.yyyy.RRRRR.yyyyyyyyyyyyyyyyyDDDDDDDDDDDDDDDDDDDDDD~~~~~~T', // 33
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....BBBB..r...rr......................................WWW..R.....RR..FggFF...BRRRR...................yyyyyF..yyyyyyyyy....RRR.yyyyyy.yyyyyyyyyyDDDDDDDDDDDDDDDDDDDDDD~~~~~~T', // 34
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG....BBBBBBrrrrrrr.......................................WW..R.....R....FFF....BRRRR............yyy....yyyyy.RR.yyyyyyy.....WWW.yyyyyyyyyyyyyyyyy...........TTTTTTTTTTT~~~~~~T', // 35
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG....BBBBBBrrrrrrr................r.........................RR....RR............RRWR....RRR...yyyyy....yyyyy.R..yyyyy.......WW...yyyyyyyy.yyyyyyy...........TTTTTTTTTTT~~~~~~T', // 36
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWBBBBBB.rrrrrr...............rrr....................WW..RR....RR........W...RRWR..RRRRR..yyyyyy....yyyyyyRRF.........BB..W....yyyy.yyyyyyyyyy...TTTTTTTTTTTTTTTTTTT~~~~~~T', // 37
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGRRRRRRR.....rrrrrr..............rrrrr....................WWRRRR...R.........W....WWRRRRR.R...yyyyyy.....yyy..RRR..BBBBBBBBB..WWW...yyyyyyyyyyyyyy...TTTTTTTTTTTTTTTTTTT~~~~~~T', // 38
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGRRRRRRRBBBBBBB..rrrr.............rrrrrrrr.....................RRRRRRR.........W....RRRRRRRR...yyyyyyy.........WWWRR.BBBBBBBBB..W......yyyyyyyyyyyyy...TTTTTTTTTTTTTTTTTTT~~~~~~T', // 39
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGRRG..RBBB..BBBB..rrr............rrrrrrrrrr......................RRRRR.........W..RRRRRR.......yyyyyy....BBBBBBWWWWR.BBBBB.....W..BB....yyyyyyyyyyy....TTTTTTTTTTTTTTTTTTT~~~~~~T', // 40
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGRGG...BBB..BBBB..rrr...........rrrrrrrrrrrr.......................RRRRR.......WRRRRRRR..F.......yy..BBBBBBBBBBRW..R.BBBBBR.WWWWWBBB...................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 41
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWRRRG...BB..........rr..........rrrrrrrrrrrrrr........................RRRR......RRRR...RR..yy.........BBBBBBB.BBRW..RRBBBBB...WW.BBBWW..................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 42
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWGWRRGG............................rrrrrrrrrrrrrrr.......................RRRRR...RRR......RFyyy..y..W......BBBB.BBRR..RRBBB...WWWBBBB.WW..................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 43
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGGRRGG............................rrrrrrrrrrrrrrrr........................RRRRRRRR..........yyyyy..WWWW.....BB.BBRR..RR.BB...WWBBBB..W...................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 44
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGGRRRG...FFFFFFFF..................rrrrrrrrrrrrrrrr.........................RRRRR.......bbb.Fyyy....W.W.....WW.BBBR..RR.BB.WW.BBBBB..W...................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 45
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWGGRRRG..FFFFFFFFFF...................rrrrrrrrrrrrrrr..........................RRR......bbbbb.Fg...F...BB....W.WBBBR..WR.BBWWW.BBBBB.WW...................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 46
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRGG..FFFFFFFFF.....................rrrrrrrrrrrrrrrr........................RRRRR.....bbbbbbbbb.....BBB..WW.W.BBRWWWR.BB.WWW..WBBWWWWBB................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 47
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWRGG..FFFFFFFFF......................rr......rrrrrrrr......................RRBB.RRRR..bbbbbbbbbb...WBBB..WWWW.BBRRRRR.....W...WWWW...BBB...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 48
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWRGG..FFFFFFFFF...........................BBB.rrrrrrrr....................RRRBB.WWWRR..bbbbbbbbbb..W.BBW.W.WWWBB.RRRR...RRRRRRRRRRR...BB...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 49
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWRRGG..FFFFFFFFF..........................BBBB..rrrrrrrr.................WWRR..B...WRRR..bbbbbbbbb.WWWBBWWW..WW.W.RRRRRRRRRRRWWW...RR..BB...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 50
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWGRRGG..FFFFFFFFF..........................BBBB...rrrrrrrrr..............WW.RR......F.RRRW.bbbb.b..b.W.BBBBBB.WWWWRRRRR..RR.BBW..BB..RR..................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 51
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWRGG..RFFFFFFFF..........................BBBBBBB..rrrrrrrr.............W..............RWW.bbb..bbb...BBBBBB............RRRBBB..BBB..R..................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 52
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWRGG..RFFFFFFFF...........................BBBBBB...rrrrrrr..........W.........rrrrr...R.W.bb...b.bb..BBBBBBBBBB.RRBBBBB.R.BBB..BBB..RR.................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 53
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGRRGG..RFFFFFFFF...............R.....R..rrr.........rrrrrrr..........W....W...rrrrrrr..RRR..b.b.b.bb..BBBBBBBBBBRRRBBBBBBR.BBBBBBBB..WRWW...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 54
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRGG..RFFFFFFFF..............RRR....R.rrrrrrrrrr...rrrrrrr........WWW....WW.rrrrrrrrr..RRR.b.....bb...BB.......RRBBBBBBBR.BB..BBBB..WR.W...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 55
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGWWRGG..RFFFFFFFF................RRR.RR.rrrrrrrrrrr.rrrrrrrr................W.rrrrrrrrrr...R..bbbbbbbb......RRRRRRRBBBBBB.R.BB....BB..WRWW...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 56
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGGWRGG..RFFFFFFFFR.................RRRR..rrrrrrrrr...rrrrrr.................Wrrrrrrrrrrr..RRR.bbbbbbbb.RRRRRRRRR.RRBBBBBB.RR.BB...BB..WRWBBB.............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 57
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWGWRGG..RFFFFFFFFR..................RRRRR..........R.....................rr..rrrrrrrrrrr..RRR.bbbbbbbb.RR.....R.BBRRBBBBBRRR.BB...BB..RR.BBBB............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 58
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRRGG..RFFFFFFFFR.......................RRRRRRRRRRRRRR..R..............rrr..rrrrrrrrrrrr..RR..bbbbbbb....BBBBBBBBRRBBBBBWRR.BB..WBB..RR.BBBB............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 59
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWRGG..RFFFFFFFFR.........................WWWWWW....RR.RRWWW.........rrrrr..rrrrrrrrrrrr..RR..bbbbbbb..BBBBBBBBBBRRWWWWWWRR.BB..WBB..RWBBB..............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 60
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWRGG..FFFFFFFFFRRW.................FF.................RRW...........rrrrr..rrrrrrrrrrrr..RRR.bbbbbbb..BBBBB......RWWWWWRRR..RWWWR...WWBB...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 61
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWRGG...FFFFFFFFRRW..W.FFFFFFFFFFFFFFFF................RRRR.rrrrrrrrrrrrrr..rrrrrrrrrrrr..RRR.bbbbbbb..BBBBB........WWWRR.RRRRRRRRBBBBWW.........B......TTTTTTTTTTTTTTTTTTT~~~~~~T', // 62
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...FFFFFFFFRRW..WFFFFFFFFFFFFFFFFFWWWWWWWWWWWW....RRR..rrrrrrrrrrrrrr..rrrrrrrrrrrr...RR.bb...bb...BBBBWW......RRRRRRRRRWW...BBBBW......BBBBB......TTTTBTTTTTTTTTTTTTT~~~~~~T', // 63
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...FFFFFFFFRRW..WFFFFFFFFFFFFFFFFFWWWWWWWWWWWW....RRR..rrrrrrrrrrrrrr..rrrrrrrrrrrr.RRRR.bb.b.bb.W.BBWWWW.......WWW..R..WBBBBBBBB..................TTTTBBTTTTTTTTTTTTT~~~~~~T', // 64
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWG.............W.WWFFFFFFFFFFFFFFFFFFWWWWWWWWWWW...WRRR..rrrrrrrrrrrrrr..rrrrrrrrrrrrRRRRR.....b.b.WWBB.W..W.....WWWBBB..WWBBBBBBBBBBB.WWBBBBBBBBBB..BBTTTTTTTTTTTTTTTTT~~~~~~T', // 65
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWG...BBBB........W.FFFFFFFFFFFFFFFFFFWWWWWWWWWWW...WRRR..rrrrrrrrrrrrrr..rrrrrrrrrrrr..WRR..b..b.b.W.BB.W..W.....W.BBBBBBRR...BBBBBBBB..WBBBBBBBBBB..BBBBBTTTTTTTTTTTTTT~~~~~~T', // 66
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...BBBB......WWW.FFFFFFFFFFFFFFFFFFWWWWWWWWRWW...WRRR..rrrrrrrrrrrrrr..rrrrrrrrrrrr..WRR.b...b.b.W.BB.W..WWWWWW.BB...BB.RRR....RR....WWBBBBBBB....WBBBBBBBBTTTTTTTTTTT~~~~~~T', // 67
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...BBB...WWWW.W..FFFFFFFFFFFFFFFFFFWWWWW..RRWW...WRRRRW.rrrrrrrrrrrrr..rrrrrrrrrrrr..WRR..bbbbbb...BB..WWWWW...BBB...BB..RRRRRRRRRWWWWWR.RRWWWW.WWWWTTBBBBBTTTTTTTTTTT~~~~~~T', // 68
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...WWW...BBW..W..FFFFFFFFFFFFFFFFFFW.WWR.RRRRW...WRRRRWW.....rrrrrrrr..rrrrrrrrrrrr..WRR..bbbbbb.......WWW.BBBBBBBBBBBB...W..RRRRRRRRRRRRRRW.......WWTWTTTTTTTTTTTTTTT~~~~~~T', // 69
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..WWWWWBBBWWW.W..FFFFFFFFFFFFFFFFFFW..RR.RRRRRR..WRRW..WWWW.....rrrrr..rrrrrrrrrrrr.......bbBBBggWWWWW..WWWBBBB..BBBBBB..WW...............WWWWW....TTTWTTTTTTTTTTTTTTT~~~~~~T', // 70
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....W.....WWWW..FFFFFFFFFFFFFFFFFFW...RRRRRRRR..WRRW..............r...rrrrrrrrrrrr.......bbBBBgg..W...W.BBWWWWWWWW.....WW..BBBBBBB...BB...W.WW....TTTWTTWWTTTTTTTTTTT~~~~~~T', // 71
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..............W..FFFFFFFFFFFFFFFFFF.W..WWRR......WRRW......BBBBBB......rrrrrrrrrrrr.......bbBBBgg.WW..WWBBBWW...W.....WWWW..BBBBBBB...BBBBBB......WWWTWWWWWTTTTTTTTTTT~~~~~~T', // 72
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.................FFFFFFFFFFFFFFFFFFWWWWWWWW..W...WRRW......BBBBBBBBB....rrrrrrrrrr...W...bbb...ggF....WBBBBW...........W....BBBBBB.....BBBBBBBB....TWTTTTTTTTTTTTTTTTT~~~~~~T', // 73
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG................FFFFFFFFFFFFFFFFFFFWWWW......WWWWWRRW......BBBBBBBBBBB....rrrrrrrr...W...bbb...ggF.....BBBBBB...............BBBB.........BBBBBB..BBBBBBBBBBTTTTTTTTTTT~~~~~~T', // 74
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG................FFFFFFFFFFFFFFFFFFWWWWWWWW.WWWWW.WRRW.....BBBBBBBBBBBBBB.WW.rrrrrrr..W...bbb...ggF...W.BBBBBB...............BBBB.........BB..BB..BBBBBBBBBBTTTTTTTTTTT~~~~~~T', // 75
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG................FFFFFFFFFFFFFFFFFFWWWWWWWWWWWWWW.RRRW.....BBBBBBBBBBBBBBWWW..rrrrr...WB..bbb...ggFWWWW.BB.WWWW...........................BB........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 76
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG................WFFFFFFFFFFFFFFFFFFWWWWWWWWWWWWW..RWW.....BBBBBBBBBBBBB..W.WW..rrr....B...bb...gFF....WBBBBBWWW....................................TTBBBBTTTTTTTTTTTTT~~~~~~T', // 77
    'GGGGGGGGGGGGGWWGGGGWWGGGGGGGGGGGGGGGGGGGG................WWWFFFFFFFFFFFFFFF..WWWWW.WWWWWW..R........BBBBBBBBBBBB.....WW......BBB........F......WWBBBBBBWW...................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 78
    'GGGGGGGGGGGGGGWWWGGGWWGGGGGGGGGGGGGGGGGGG..................W..RRRRRRRRRRRR......WWW..........b......BBBBBBBBBBBB...W.W....RRR.R.................WW..BBBBWW..................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 79
    'GGGGGGGGGGGGGWWGGGGGGWGGGGGGGGGGGGGGGGGGG..................W.BBBBBBBBBBBBBBBBBBBBW..........b.......BBBBBBBBBBBW...WWW...RRWWRR......BB..........WWW..BBW...................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 80
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........FFFFFFWWWBBBBBBBBBBBBBBBBBBBB........R..b...bbb..BBBBBBBBBBW.W.W.....RW.WWR.....BBBB.....BB.WW.WWWBB.W..................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 81
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..........FFFFFFFFW.BBBBBBBBBBBBBBBBBBBB........R.bb...bb...BBBBBBB..WWWW......RRWWWWR....BBBBB...BBBB.WWWWW.BBWW..................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 82
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........FFFFFFFFFFWWBBBBBBBBBBBBBBBBBBBB.......RR..b...bb....BBBBBBWWWRRW.....RR....WRRR..BBBBBBBBBBB...WWW.BBBW...................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 83
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGGGGGGGGG........FFFFFFFFFFW.BBBBBBBBBBBBBBBBBBBB.......RR..b...bb...BBBBBBBWW.WRR....RR.....W..R..BBBBBBBBBBB....W.BBBB....................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 84
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWGGGGGGGG.......FFFFFFFFFFFW.BBBBBBBBBBBBBBBBBBBB......RRR......b..BBBBBBBBBWWWWWRRRRRR......WR....BBBBBBBBBBB...WWBBBBBBBB.................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 85
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWGWWGGGGGG......FFFFFFFFFFFFW.BBBBBBBBBBBBBBBBBBBBB......RR........BBBBBBBBBBBWWRRRRR.........WRR...BBBBBBBBBBB...WWBBBBBBBB.................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 86
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWGGGGGGG......FFFFFFFFFFF.W.BBBBBBBBBBBBBBBBBBBBB......R........BBBBBBBBBBBBBWRWW...........WRRR..BBBBBBBBBBBW....BBBBB..W.................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 87
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGGGGGGGG......FFFFFFFFFFF.W.BBBBBBBBBBBBBBBBBBBBB...............BBBBBBBBBBBBBWWWW...........WRRR..BBBBBBBBBBBWWRR.WBBBBBBWW................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 88
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......FFFFFFFFFFFWW.BBBBBBBBBBBBBBBBBBBBB................BBBBBBBBBBBBW..W...........WRR...BBBBBBBBBBBW.RRWWWBBBBBBWW...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 89
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWWWWGGGGG......FFFFFFFFFFF.W.BBBBBBBBBBBBBBBBBBBBWWW.B.............BBBBBBBBBBBBBBBB..........WRR...BBBBBBBBBBB...RRWW....BBBW...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 90
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGWGGGGGGG.......FFFFFF..F...WWBBBBBBBBBBBBBBBBBB.WW.BB.............BBBBBBBBBBBBBBBBBBB.......RRR...BBBBBBBBBBBBB.RRRW.....BB................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 91
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............WWWWWWWWW..........BBBBWWW..B...............BBBBBBBBBBBBBBBBBB.......RRR...BBBBBBBBBBBBB..RRRW.....W................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 92
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.................FFFFWWWW..............WW..........BBBBB...BBBBBBB..WBBBBBBB........RRR...BBBBBBBBBBBBBB..RRWWW.WWWW...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 93
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............FFFFFFFFF.WW.................b......BBBBBBBBBBBB...WWWWWBBBBB..W.....RRR.W.BBB.....BBBBBBB.....W.........WW.........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 94
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..............FFFFFFFFFFF.W................bbb....BBBBBBBBBBBB..WWWW..WWWBBB.WWWW..RRR..WWBBB.....BBBBBBB.....W..........WW........................TTTTTTTVTTTTTTTTTTT~~~~~~T', // 95
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..............FFFFFFFFFFFFW...............bbbb.WWWBBBBBBBBBBBBWW.WWW...WWW.........RRRRRRWBBB.......BBBBB...BBBBBBBBBBBBB.W........................TTVVVVVVTTTTTTTTTTT~~~~~~T', // 96
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.............FFFFFFFFFFFFFFFFWW....W.....bbbbb.W.WBBBBBBBBBBBBWWWWWWW..............RRRRRRRBBBBWW..WWBBBBB...BBBBBBBBBBBBB.W........................VVVVVVVVTTTTTTTTTTT~~~~~~T', // 97
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG............FFFFFFFFFFFFFFFFF.WWW.WW....bbbbbb.BBBBBBBBBBBBBBB..WWWWW..............RR..RRRBBBB.WWWW.BBBBB.W.BBBBBBBBBBBBB.W......................VVVVVVVVVVTTTTTTTTTTT~~~~~~T', // 98
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........FFFFFFFFFFFFFFFFFFFWWW.W.....bbbbb..BBBBBBBBBBBBBBB..WWWWW.............RRR.....BBBB.W.WW.BBBBB.W.BBBBBBBBBBBBB.......................VVVVVVVVVVVTTTTTTTTTTT~~~~~~T', // 99
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..........FFFFFFFFFFFFFFFFFFFFWW.WW....bbbbbb..BBBBBBBBBBBBBB...W.................RRR..........WWWW.BBBBB.W.BB..BBBBBBBBB..W...................VVVVVVVV~~~~TTTTTTTTTTT~~~~~~T', // 100
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..........FFFFFFFFFFFFFFFFFFFF...WR...bbb.bbb.BBBBBBBBBBBBBBB....................RRR......BBBB.WWWW.BBBBB.W.....BBBB.......WW.................VVVVVVV~~~~~~TTTTTTTTTTT~~~~~~T', // 101
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........FFFFFFFFFFFFFFFFFFFFF...RR..bb....b..BBBBBBBBBBBBBBB.W.......BBB........RRR......BBBB.WWWW.BBBBB.W.BBBBBBBBBBB....W.BB..............VVVVVV~~~~VVVVTTTTTTTTTTT~~~~~~T', // 102
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........FFFFFFFFFFFFFFFFFFFF...RR..bbbb..bb.BBBBBBBBBBBBB..WWW......BBBBB......RRRRR....RBBBBWW.WW.BBBBB.W.BBBBBBBBBBBBB..WWBBBBB...........VVVVV~~~VVVVVVTTTTTTTTTTT~~~~~~T', // 103
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........FFFFFFFFFFFFFFFFFFFF...RR.bbbbb..bb.BBBBBBBBBBBBB..........BBBBBBB.....RRR..RR..RRWWWWWWWWW....WWWWBBB....BBBBBB..W.BB.............VVVVV~~VVVVVVVVTTTTTTTTTTT~~~~~~T', // 104
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........FFFFFFFFFFFFFFFFF..FFR..bbbbb..bb.BBBBBBBBBBBBB.........BBBBBBBBB...RRR....RRRRRRW.W.BBBBB...W.W.......W....WWW...BB.............VVVVV~VVVVVVVTTTTTTTTTTTTT~~~~~~T', // 105
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........FFFFFFFFFFFFFFFFF...RR..bbbbb.bbbb..BB...BB............BBBBBBBBBBW..RRR......RRRRRWWBBBBBB...W.WWW.WWWWW....WWW.................VVVVV~~VVVVVTTTTTTTTTTTTTTT~~~~~~T', // 106
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG............FFFFFFFFFFFFFFFF..RR....bbbbbbbbbbb...WWW.WWW..WW....BBBBBBBB..WWWRRR.......RRRRRRWBBBBBB...W.W.W..W.......W................VVVVVVVV~VVVVVTTTTTTTTTTTTTTTT~~~~~~T', // 107
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.............FFFFFFFFFFFFFF...........bbbbbbbbbbbb.WWWWW.FFFWW.BBBBBBBBBB..WWRRRR......RRRRRRRWBBBBBBWWWWW...........BBBBB......VVVVVVVVVVVVVVV~~VVVVTTTTTTTTTTTTTTTTT~~~~~~T', // 108
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..............FFFFFFFFFFFF.........W...bbbbbbbbbbbb.WW.WFggFFWWBBBBBBBBB...WRRRRW....RRRRRRRRRWBBBBBBW..WW..WBBB.....BBBBB...VVVVVVVVVVVVVVVVVV~VVVVVTTTTTTTTTTTTTTTTT~~~~~~T', // 109
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............FFFFFFFFFF.W...RR..WWWW..bbbbbbbbbbbb.WFFggggFW.BBBBBBBB....RRRRWW...BBBRRRRRRRRBBBBBB...W..WWBBB.....BBBBBVVVVVVVVVVVVVVVVVVVV~~VVVVTTTTTTTTTTTTTTTTTT~~~~~~T', // 110
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.................FFFFFFFFWW...RR..W......bbbbbbbbbb..FFggggF.W.BBBBBBB...WWRRR..W...BBBRRRRRRR..BBBBB..WW..WBBBB.....BBBBBVVVVVVVVVVVVVVVV~~~~~VVVVVTTTTTTTTTTTTTTTTTT~~~~~~T', // 111
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..................FFFFFFWW...RRRR...rr.....bbbbbbbb..FggggFF.BBBBBBBB...WWRRR...W...BBBBBBBBB.WWBBBB........BBBB....VVVVVVVVVVVVVV~~~~~~~~~~~~~VVVVTTTTTTTTTTTTTTTTTTT~~~~~~T', // 112
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........................W....RRR...rrrr.....bbbbbb..FggggF..BBBBBBWWW...RRRRW......BBBBBBBBBB.WW.................VVVVVVVVVVVVVV~~~~~~~~~~~VVVVVVVVVTTTTTTTTTTTTTTTTTTT~~~~~~T', // 113
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...................BBBB......RRR..rrrrrrr....bbb...FgggggF.BB.....WWW..RRRRWWWW....BBBBBBBBBBBW..............VVVVVVVVVVVVVV~~~~~~~VVVVVVVVVVVVVVVV.TTTTTTTTTTTTTTTTTTT~~~~~~T', // 114
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....................B.......RR..rrrrrrrrr....bb..FgggFFFgFBB.....W...RRRRWWWWWBBBBBBBBBBBBBBB.WW...........VVVVVVVVVVVV~~~~~~~VVVVVVVVVVVVVVVVVV..TTTTTTTTTTTTTTTTTTT~~~~~~T', // 115
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...........................RRR..rrrrrrrrrrr.......FggggggggFBBBBB.WWW.RRR..WW.BBBBBBBBBBBBBBBB.W.........VVVVVVVVVVVVV~~~~~VVVVVVVVVVVVVVVVV.......TTTTTTTTTTTTTTTTTTT~~~~~~T', // 116
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..........................RR..rrrrrrrrrrrrrr.....FgggFggFFggFBBBBWW...RWW..W..BBBBBBBBBBBBBBBBWWW.....VVVVVVVVVVVVV~~~~~VVVVVVVVVVVV...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 117
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........................RR..rrrrrrrrrrrrrrrr....Fgg.FFgFFgggFBB......WW...W..BBBBBBBBBBBBBBBB..WW..VVVVVVVVVVV~~~~~~~VVVVVVVVVVV..................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 118
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........................RR..rrrrrrrrrrrrrrrrr.....FgggFgFgggF.W......W.....W..BBBBBBBBBBBBBBBBWW==VVVVVVVVVVVV~~~~~VVVVVVVVVV......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 119
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........................RR.rrrrrrrrrrrrrrrrr...b...FFggggggFF.WW....WWWWWWWWWWBBBBBBBBBBBBBBBBWWV==VVVVVVVV~~~~VVVVVVVVVVV.........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 120
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG........................RRrrrrrrrrrrrrrrrrr...bbb....FggggFF..W....W....BB.W.BBBBBBW..WW......WVV==VVVVV~~~~~~VVVVVVVVVV...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 121
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRRrrrrrrrrrrrrrrrrr..bbbbb...FFggFF......W.W...BBBBBBBBBBBBW...W.WW...VVVV==VV~~~~~VVVVVVVVVV..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 122
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRRrrrrrrrrrrrrrrr...bbbbbbbb...FFF...R..WWWW..BBBBBBBBBBBBBW...WWWW..VVVVV==~~~~VVVVVVVVV........ttt.......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 123
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRRrrrrrrrrrrrrrrr..bbbbbbbbbb..RRR..RR.WWW.W..BBBBBBBBBBBBBW.WWW....VVVVVV~==~VVVVVVVVVV........ttttt......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 124
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRRrrrrrrrrrrrrr...bbbbbbbbbbb...RRRRR.W...WW..BBBBBWW.BBBBWWWW.....VVVVVV~~==VVVVVVVV...........ttttt......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 125
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRRrrrrrrrrrrrr...bbbbbbbbbbb......R..WW..WWWWWBBBBBWWW..WWWW.......VVVVV~~VV==VVVV...ttttttttttttttttt.....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 126
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRRrrrrrrrrrr.....bbbbbbbbbbb......RR..WWWWWWWWBBBBBB..W.WWWWW.....VVVVV~~VVV==VV....ttttttttttttttttttt....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 127
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RR.rrrrrrrr.....b.b..bbbbbbb......RRRWWW..W.W.WBBBBBBW.WWWWWWW.....VVVVV~VVVVV==.....ttttttttttttttttttt....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 128
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RR..rrrr........bb..bbbbbbb......RRR...WW..WW..BBBBBWWW............VVVV~~VVVV.==...ttttttttttttttttttttt....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 129
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRR.........rrr.bb...bbbbb.......RR.....WW..WBBBBBBB...............VVVV~VVVVV..==tttttttttttttttt.ttttt.....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 130
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................RRR.....rrrrrrrr.b.b.bbbb.......RRR......WW.WBBBBBBBW..............VVVVVVVVVtttttttttttttttttttttttttt......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 131
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR.rrrrrrrrrrrrr.b...bbb.......RRR........WWWBBBBBBBW...............VVVVVVVtttttttttttttttttttttttttt.......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 132
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR.rrrrrrrrrrrrrrbbbbbb........RRR.........WWBBBBBBBWWW...WWW........VVVVVttttttttttttttttttttttttttt.......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 133
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR.rrrrrrrrrrrrr..bbbb...W....RRR...........WW......WWW.WW..WW.........ttttttttttttttttttttttttttttt........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 134
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR.rrrrrrrrrrrr...bb.....W....RRR............WW.....W.BBBWW............tttttttttttttt.t.tttttttttttt........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 135
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR.rrrrrrrrr...WW........W....RRW............WWW...WWWBBBW.............ttttttttttttttttttttttttttttt........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 136
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR..rrrrr.......WWWWW....WW..RRRW.............WW....WWBBBB.............tttttttttttttttttttttttttttttt.......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 137
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR........................W..RRRW.............WWW..WW..BBBB............ttttttttttttttttttttttttttttt........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 138
    'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG......................WRR.....................WWWW..RRRW.............WW..W.WWWBBBB............ttttttttWtttttttttttttttttttt........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 139
    'GGGGGGGGGGGGGGGGGGGGWGGGGGGGGGGGGGGGGGGGG......................WRR.......................WWWWRRWW..........WWW.W..WWW.WBBBBBBB.........ttttttttWtttttttttttttttttt..........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 140
    'RRRRRRRRGGGGGGGBBWWWWBBGRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR..WWRRRRRRRRR.....WWWWW......RRRRRRRRWWWW..........W..WWWWWW..W..BBB.........ttttttttWWtttttttt...................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 141
    'RRRRRRRR.......BBBBBBBB.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWRRRFRRRRRR......BBBBB.....RRRRRRRR.WWWW...WW.......WWWKKWW.W..............tttttttt.Wtttttt.....................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 142
    'RRRRRRRRRRR...........RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW.RRRRRRRRRRRRR...........RRRRRRRRRR.WWWWWWWWWWWWWWWWW.WKKWWWWWWW...........tttttttt..ttttt..BBBBB...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 143
    'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRR...WWWWWWWWWWRR....BBB..RRWW....WWWWWW.....WWWWWWWWWRRR.WWW..WWWWW.WWWW...WWWWWW...WWW.........FFFFFFFF..FFFFWWBBBBBB...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 144
    '....................................RRRR.............RR....BBB.RRRW........................WRRRWW..WW...W..WWWW..W..W.WWWWWWWW.........FFFFFFF.WWWWWWWWBBBBBB..BB...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 145
    '....................................RRRR..............R........RRRW.....................WWW.RRR.W...WWWW...WWWWWWWWWW..WWW...WWW........FFWWWWWWWW...BBBBBBB..BBB...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 146
    '....................................RRRR..............RR.......RRRW......................W..RRR.W.WWWWWW.W.WW.....WWW.WW.WW...WW.WWWWW......W..WW....BBBBBBB..BBB...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 147
    '....................................RRRR................RRR....RRRW......................W..RRR...BBBB.W.WWW........WWW..WWWWWW.~~~~.W......W..WW....BBBBBBB..BBB...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 148
    '...................................WW.RR.................RRR...RRR.................WW....WW..RR..BBBBBBBBBB..BBBBBBB.WBB...WWW.~~~~~~BBBBBBWWWWWWW...BBBBBBBBBBBB...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 149
    '...................................W..RR...BBBBB..........RRR..RRR....rrrrr........WW.....W..RR..BBBBBBBBBB..BBBBBBBBBBBWWWW.W.~~~~~~BBBBBB.WWWWWWWW.BBBBBBBBBBBB...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 150
    '..FFFFFFFFFFFFFF.......WW..W...WWWWW..RR...BBBBB...........RRR.RRR...rrrrrrrrrr....W......W..RRR..BBBBBBBBB..BBBBBBBBBBBWWWWWW.~~~~~~BBBBBB.WWWWWWWWWWWW..WWBBWW............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 151
    '.FFFFFFFFFFFFFFFFF....WWW.WWWWWW..W...RR..BBBBBB............RR.RRR...rrrrrrrrrrrr............RRR..BBBBBBBBBWWBBBBBBBBBBBBW...........BBBBBB.W.WWWWWW...W...W...WW...........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 152
    '.FFFFFFFFFFFFFFFFFF.W.WW......WW...W...RRRBBBBBB.........BBB.RRRRR.rrrrrrrrrrrrrr.............RRWWBBBBBBBBBWWWBBBBBBBBBBB............BBBBBB............W..WW................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 153
    '.FFFFFFFFFFFFFFFFFFWWW..RRRRRR.....W...RRRBBBBBB...........WWWWRRRrrrrrrrrrrrrrrr.bbb.........RRRW...WWW...WWWBBBBBBBBBBB..........WWWBBBBB.WWWWWWW....W.BBBBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 154
    '.FFFFFFFFFFFFFFFFFFF...RRFFFFRR....W....RRBBBBB..............W.RR.rrrrrrrrrrrrrrr.bbbbb........RRW...W.WWWW..BBBBBBBBBBBBW.....~~~.WW.BBBBBW......W....W.BBBBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 155
    '.FFFFFFFFFFFFFFFFFFWW..FFFFFFFF....W....RRRRR..................RR.rrrrrrrrrrrrrrr..bbbb........RRR..WWWW..W..BBBBBBBBBBBWW....~~~~WWR.BBBBBWW....WW....W....................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 156
    '.FFFFFFFFFFFFFFFFFFW...FFFFFFFFF....W..........................RR.rrrrrrrrrrrrrrrrr..bbbb....WWWR.....WW...WWBBBBBBBBBBB.WW...~~~~.WR.BBBBBWWW........WW.......W............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 157
    '.FFFFFF.FFF.FFFFFFFW..FFFFFFFFFF...WW..........................RR.rrrrrrrrrrrrrrrrrrr.bbbbb..WW......WWW.RWWWBBBBBBB..BB.WW....~~~.RR.BBBBBWWW.WWWW....W.BBBBB.W...................r........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 158
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF...WW..........................RR.rrrrrrrrrrrrrrrrrrrr.bbbbb...WW..R..WWRRW.BBWWWWW.WW.WW.WWWW.WW..WRWWWWWWWWWWWWWWWWW.W.BBBBBWW..................oor.......TTTTTTTTTTTTTTTTTTT~~~~~~T', // 159
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WWWWWWWWWWWWWWWWWWWWWWWWWWWRR.rrrrrrrrrrrrrrrrrrrrrr.bbb.WWWW..RRRRRRR..BBWWWWWWWWWW...W.WWWWWWWR....WWWWWWWWWWWWWWWWWWWW..W..................or........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 160
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WWFFFFFFFFFFF..FFFFFFFFF...RR.rrrrrrrrrrrrrrrrrrrrrrr......WWW.RRRRRRRRR.RRR..WWW..WWW.W...W...WR...WWW..WWWWWWWW....W.WWWW..................rr.........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 161
    '.FFFFFFFFFFFFFFFFFFF..FFFFFFFFFF....WWFFFFFFFFFFF..FFFFFFFFFF..RR..rrrrrrrrrrrrrrrrrrrrrrr.......WR..RWWW.RRRRRRRRWWWW.WWWW..WWW...WR.......WWWWWWWWBBBB........................rrr.........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 162
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WWFFFFFFFFFFFFFFFFFFFFFFF...RR....rrrrrrrrrrrrrrrrrrrrr......RRR.RRW...RR....B.RW......WWW.....WR....BBBBWWWWWW.BBBB........................or..........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 163
    '.FFFFFFFFFFFFFFFFFF...FFFFFFF.FF....WWFFFFFFFFFFFFFFFFFFFFFFF..RRR.r......rrrrrrrrrrrrrrrrrr....RRRWW.......R....BRRRW.BWWWWWW.....WR.WBBBBBBW.WWWBBBBBB........................r...........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 164
    '.FFFFFFFFFFFFFFF.BB...FFFFFFFFFF....WFFFFFFFFFFFFFFFFFFFFFFFF.WRR.rrrrrrr...rrrrrrrrrrrrrrrr...RRR..W...........BB.RRWBBW...W...WWWWRWWBBBBBBWWWW.BBBBBB............................BBBBB...TTTTTTTTTTTTTTTTTTT~~~~~~T', // 165
    '.FFFFFFFFFFFFFFBBBB...FFFFFFFFFF....WFFFFFFFFFFFFFFFFFFFFFFFF.WR..rrrrrrrrr...rrrrrrrrrrrrr.....F...W............RRRRWBB.W..W....WWWRW.BBBBBB.WWW..............................b....BBBBBB..TTTTTTTTTTTTTTTTTTT~~~~~~T', // 166
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WFFFFFFFFFFFFFFFFFFFFFFFFFWR......rrrrrr....rrrrrrrrrr.WW.FFF.......BB.......WRRRW...W.........WR..BBBBBB..WW.........................bb..bb.....BBBBB..TTTTTTTTTTTTTTTTTTT~~~~~~T', // 167
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WFFFFFFFFFFFF.FFFFFFFFFFFFWWB......rrrr......rrrrrrrr.WW..ggFF......BBB.R....WWRRRW.WWBB.......RR..BBBBBB..WW.........................b....b.....BBBBB..TTTTTTTTTTTTTTTTTTT~~~~~~T', // 168
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WFFFFFFFFFFFF.FFFF.FFFFFF..BB.....rrrrrr..rrrrrrrrrrWWW..bbFgFF......RRRRR....WRRRWWBBBB......RRR........WWWW........................bb...........W.BB..TTTTTTTTTTTTTTTTTTT~~~~~~T', // 169
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF....WFFFFFFFFFFFF.FFFFFFFFFFF...B.W...rrrrr...rrrr..rrr.W..r.bbbggFF......RRR......RRRWBBBBBBBBBBRRRRR...WWW.W.W.W.......................bbb..........WW....TTTTTTTTTTTTTTTTTTT~~~~~~T', // 170
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF...WWFFFFFFFFFFFFFFFFFFFFFFFF..WB.WW...rr.rr..rrrr..rr....rrr.bbbggF...F...RRR.....RRWWBBBBBBBBBBRRRR..WWWWWWWWWWWW......................bbbbb....BB...WW...TTTTTTTTTTTTTTTTTTT~~~~~~T', // 171
    '.FFFFFFFFFFFFFFFFFF...FFFFFFFFFF...WWFFFFFFFFFFFFFFFFFFFFFFFF..W...WW.....rrrrrrrrr......rrrrr.bbbggF.......RRR....RR.WBBBBBBBBBBRRRRR....W...W..WWW.......................bb.....BB...WBBBBBBBTTTTTTTTTTTTTTTT~~~~~~T', // 172
    '.FFFFFFFFFFFFFFFFFF....FFFFFFFF..WWWWFFFFFFFFFFFFFFFFFFFFFFFF..WWW..W......rrrrrrrr..F..rrrrrrr.bb.ggF......RRRR.RRRWWWBBBBBBBBBBRRWRR.......BBBBB.W..............................BBBBBBBBBBBBBBTTTTTTTTTTTTTTT~~~~~~T', // 173
    '.FFFFFFFFFFFFFFFFFF....FFFFFFF...WWW.FFFFFFFFFFFFFFFFFFFFFFFF.......WWW.....rrrrr......rrrrrrrr...bgggF......RRRRRRWWWWBBBBBBBBBBRRWWR....W..BBBBBBWW.BBBBBBBBBBBB................BBBBBBBBBBBBBBTTTTTTTTTTTTTTT~~~~~~T', // 174
    '.FFFFFFFFFFFFFFFFFFF.....FFFF....WWW.FFFFFFFFFFFFFFFFFFFFFFFF...W...W..WWW....rrr....rrrrrrrrrr...bbFgFF......RRRRWWWW..BBBBBBBBBRRRWR....W..BBBBBBWW.BBBBBBBBBBBB...bb.........WWWBBBBBBBBBBTTTTTTTTTTTTTTTTTT~~~~~~T', // 175
    '.FFFFFFFFFFFFFFFFFFF..................FFFFFFFFFFFFFFFFFFFFFFF..WWWW.....WWW.........rrrrrrrrrrr....bbggF......RRRRWW.WBBBBBBBBBBRRRRWRR...WW.BBBBBBWW..BBBBBBBBB...bbbb.........W.WBBBBBBBBBBRTTTTTTTTTTTTTTTTT~~~~~~T', // 176
    '.FFFFFFFFFFFFFFFFFFF..WW..............FFFFFFFFFFFFFFFFFFFFFFF....WW....BBBB.....W..rrrrrrrrrrr......bbggFF...RRRRRRW..BBBBBBBBBRRRRRRRR...W..BBBBBBW.....BBBBBB...bbbbb.........W..BBBBBBBBBBRTTTTTTTTTTTTTTTTT~~~~~~T', // 177
    '.FFFFFFFFFFFFFFFFFF...WWWW...WWW.W.....FFFFFFFFF..FFFFFFFFFF.....WWWW...B......WW.rrrrrrrrrrrrr....r.b.ggF..RR..RRRW..BBBBBBBBBRRRRRRRR......BBBBBBW.....BBBBBB...bbbbb.....RRR....BBBBBBBBBBRTTTTTTTTTTTTTTTTT~~~~~~T', // 178
    '.FFFFFFFFFFFFFFFFFF...WBB.WWWWWWWW...................................W.......RRWrrrrrrrrrrrrrrrrrrrrr.bgF.RRR....RRR...BBBBBBBBR...................W.....BBBBB....bbbbb...RRRR.BBBBBBBBBB...TRRTTTTTTTTTTTTTTTT~~~~~~T', // 179
    '.FFFFFFFFFFFFFFFFFF....BBB.......................................BB.WW.......RR.rrrrrrrrrrrrrrrrrrrrrr...RRR......RRR..BBBBBBBBR..................................bbbbb...RR.BBBBBBBBBBBB...RRRRTTTTTTTTTTTTTTT~~~~~~T', // 180
    '...FFFFFFFFFFFFFF...............................................BBBWWWW.WWW..RR.rrrrrrrrrrrrrrrrrrrrrr..RR.........RRWWBBBBBWW...............bbbbbbbb............bbbbbb..RR.BBBBBBBBBBBBBB.RTTTRRTTTTTTTTTTTTTT~~~~~~T', // 181
    '...........................W...................................BB.WW..WWW.W..RR.rrrrrrrrrrrrrrrrrrrrr..RR..........RRRWW.BBBWW...............bbbb...bbbbbbbbbbbbbbbbbb...R..BBBBBBBBBBBBBB.RTTTTRTTTTTTTTTTTTTT~~~~~~T', // 182
    '..........................WWW.................................BBBWWBB.....W...RR.rrrrrrrrrrrrrrrrrr......bbbb.......RRRWWBBB.W...............bbbb..bbbbbbbbbbbbbbbb.........BBBBBBBBBBBBB.RRTTTRRTTTTTTTTTTTTTT~~~~~~T', // 183
    '..........................WW................................BBB.W.BB....BBWW..RRR.rrrrrrrrrrrrrrrr.F....bbbbbb......RRRW.....WW........FF....bbbb....bbbbbbbbbb....RRRRR....BBBBBBBB......RRTTRRTTTTTTTTTTTTTTT~~~~~~T', // 184
    '..........................WW...............................BBBWWW.B......BBWW...RR.rrrrrrrrrrrrrr..F.....bbbbbb......RRR..FFFFFFFFFFFFFFFFF..bbbb....bbbbbbb....RRRRRRRRRRR..............RRRRRRTTTTTTTTTTTTTTTT~~~~~~T', // 185
    '...........................................................B.WWBB..W.....BB.WWW.RR..rrrrrrrrrrr.......rr..b.bbbb......RRR.FFFFFFFFFFFFFFFFF..bbbb.b.bbbb.....RRRRR..R....RRRRRRRRRRRRRRRRRRRTTTTTTTTTTTTTTTTTTT~~~~~~T', // 186
    '.............................................................WBBB..WB...WWWBBB.WWR...rrrrrrrrrr.....rrrrr....bbbb......RR.FFFFFFFFFFFFFFFFF..bbbbbb..........WWR.............RRRRRR.........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 187
    '.............................................................BBB..WWBB....WBBBWW..RR..rrrrrrr....F.rrrrrrr..bbbbbb.....RRRFFFFFFFFFFFFFFFFF.bbbbb..........WWWW..b...b......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 188
    '..........................................................W..BB..BBWWBB...BBB..WF..RR..rrrrr.......rrrrrrrr..bbbbb......RRFFFFFFFFFFFFFFFFF...............BBB.WW.b.b.b......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 189
    '..........................................................W......BBB....BBB.........R..rrrr.RR...rrrrrrrrrr.bbbbbbb.....RRRFFFFFFFFFFFFFFFWR........WW....BBB....b...b......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 190
    '........................................................WWWBB.....BB....BB..........RRR.r..RRR..rrrrrrrrrrr..bbbbbbb....RRRWFFFFFF..FFFWWWWRRRRRR....W..BBBBBBBB.b...b......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 191
    '.........................................................WWBBB.....B.....W...........RRR..RR..rrrrrrrrrrrr....bbbbbb.WWWWRRWWWRRRRRRRRRRRRRR..R.....WW..BBBBBBBB.b...b......................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 192
    '............................................................BBB....BBB...WW......BBWW.RRRRR..rrrrrrrrrrrrr..rr.bbbb..WWWWRRRRRRRRRRRRRRRRRRW.......WWWWWBBBBBBBBBBBB........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 193
    '........................................................yy...BBB...BBB...W....W.BBB.W..RRR..rrrrrrrrrrrrrrrrrr..b....RRRRRRRBB.W..........WWW....BBBBBB....BB...BBBB........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 194
    '.......................................................yyyy.F.BBB..BBBWW..WWWWWBBB.WWWWWRR..rrrrrrrrrrr.rrrrrrr....RRRRWWRRRBB.WW...........BBBWWWW........BB...BBBBBBBB....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 195
    '.......................................................yyyyy...BB....WWWW.W.W.BB...BB.WWWR..rrrrrrrrrrrr.rrrr......WWW..WWRRBB.W............BBB..BBBBBB....BBBBBBBBB..BB....................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 196
    '.......................................................yyyyyy...B..WWW...W.WWBBB...BBBW...R..rrrrrrrrrrrr....FB...WWWWW.WWRRRWW..BBBBBB..BBBBBB..BBBBBBBBBBBBBBBBBBB........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 197
    '.......................................................yyyyyyy....WW.W..WWW.WBBB....BBW.W.RRF.rrrrrrrrrrr.W..BBBWWW..BBBWWRRRW..BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 198
    '.......................................................yyyyyyy...W....W.WW..WWBB........W..RR..rrrrrrrrr.WWW.B.WWWW..BBB.WRRRW..BBBBBBBBBBBBBBBB....BBBB..BBB...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 199
    '.......................................................yyyyyyyy.WWBBB.WWWBBB.WBBB.......WWWWRRR.rrrrrrr.........WW........RRRR..BB.....BBBBBBBB.....BBBB..BBB...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 200
    '............................WWW........................yyyyyyy..W.BBB.W..BBB...BBB.BBB..BBWWWRR.rrrrrr......yyy..WW.......RRRRR.BB.....BBBBBBBB.....BBBBB.BBBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 201
    '.............................WWW.......................yyyyyyy..WW...WW.....BB..BB.BB...BBB.WWRR.rrrr......yyyyy..BBBB....RRRWRWBB...........BB.....BBBBB.BBBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 202
    '.................................WWWWW.................yyyyyyy...W..........BBB..........BB..WRRR....R....yyyyyyy.BB.RR.....WWRWBBBBBBBB.BBBBBB......BB.....................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 203
    '...................................RRW..................yyyyyyy..............BB..............W.RR...RR..yyyyyyyyyy....R....RRWRWBBBBBBBB.BBBBBB.............................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 204
    '.................................W.WRR.................B.yyyyyyy...y...W...........BB........WWWRRRRR..yyyyyyyyyyyy.RRRW...RWWRWBBBBBBBB.BBBBBBBB..W..........................BBBBB.........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 205
    '................................WWWWRR.................BB.yyyyyy..yyy..WBB..........BB....BB..WWWRR...yyyyyyy.yyyyy.FRWW...RRRR.BBBBBBBB....BBBBB..WWWW........................BBBB.........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 206
    '....................................R..................uBB.yyyyyyyyyyy.W.BB..........BB..BBBWWWWW.RRR.yyyyyyyyyyyyyy.RW.....RR..BBBBBBBB....BBBBB.....W.........................WW..........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 207
    '....................................R..................uuu.yyyyyyyyyyyyWWBB.......B..W..BBB.WW..W.WRR..yyyyyyyyyyyyy.RR.....R...BBBBBBBB.BBBBBBBBWWW............................WW..........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 208
    '....................................R..................uuu..yyyyyyyyyyyy..........BBWW..BBW.....WWW.R..yyyyyyyyyyyyyRRRR....R...BBBBBBBB.BBBBBBWWWW.....................WWWWWBBBBBBBBBB.....TTTTTTTTTTTTTTTTTTT~~~~~~T', // 209
    '...................................RR..................Buuu..yyyyyyyyyyy....BB.....BWWW..WW.....WWW.BB..yyyyyyyyyyyyR.RRR..BR...BBBBBBBB.BBBBBBWWW...........................BBBBBBBBBB.....TTTTTTTTTTTTTTTTTTT~~~~~~T', // 210
    '...................................R..................BBuuuu..yyyyyyyyyyy...BBBF...BBB..WW......WW..WBB..yyyyyyyyyy...RRR.BBR.W....W....W...W..W............................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 211
    '...................................R..................Buuuuuu..yyyyyyyyyyy...BB....BBB...W....WWBBB.WWBB..yyyyyyyyy.F.RR..BBRWWWWWWWWWWWWWWWWWW..........................WWW................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 212
    '...................................R..................Buuuuuu...yyyyyyyyyyy.WW....BBBWWW.WWWWWWBBBBBWWW....yyyyyyy..RRR....RR.WW.....W..WW..WW..........................WW...BBB..BB........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 213
    '..................................RR....................uuuuuuu..yyyyyyyyyyy.WWWWBBBWW..WW..WWBBBBBBB.W....yyyyy..RRR.F.....RW...BBBBBB.W.WW............................W....BBBBBBB........TTTTTTTTTTTTTTTTTTT~~~~~~T', // 214
    '..................................RR...................uuuuuuuu..yyyyyyyyyyyy.WW...WW...W...W.BB...BBBWW....yy..RRR....yyy..RW..BBBBBBBBWWWW................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 215
    '..................................R.....................uuuuuuuu..yyyyyyyyyyyy.W.WW..W..WW.WW....W..BB.WW.....RRR...y..yyy..RWWWBBBBBBBBW..W............................BBB.................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 216
    '..................................R.....................uuuuuuuuu..yyyyyyyyyyy..WWBB.WW.WW..WWW..WW.....WW..F.R...yyyy.yyy..RRW.BBBBBBBWW...............................BBBB.BBBBBBBB.......TTTTTTTTTTTTTTTTTTT~~~~~~T', // 217
    '..................................R....................Buuuuuuuuuu..yyyyyyyyyyy.W.BBBWW.WBBBWW.BBWW.....WW......yyyyyy.yyy.RRRR.BB.BBBB.................................BBBB.BBBBBBBB.......TTTTTTTTTTTTTTTTTTT~~~~~~T', // 218
    '..................................R....................Buuuuuuuuuub.yyyyyyyyyy..W.BBB.W.BBBBBWWBB.WWW....W....yyyyyyyy.yyy.RR.R.BB..BBB.W...............................BBB.................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 219
    '..................................R....................Buuuuuuuuuuuu..yyyyyyyy..W..BB..BBB..BB.W..WWWBB.......yyyyyyyy..yy.RR.R.BBBBBBBBW...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 220
    '..................................RW...................Buuuuuuuuuuuuu.yyyyyyyy..............BBBWWWW.BBB........yyyyyyyy.yy.RR.R.BBBBBBBBW...............................BB.WW...............TTTTTTTTTTTTTTTTTTT~~~~~~T', // 221
    '..................................RW...................Buuuuuuuuuuuuuu.yyyyyyy...............BB.WWBBBB.........yyy..yyy.yy.RR.R.BBBBBBBBW...............................BB..WBBBB.BBBBB.....TTTTTTTTTTTTTTTTTTT~~~~~~T', // 222
    '..................................RW...................Buuuuuuuuuuuuuu..yyyyyyy........W.......WWBBBB..........yyy.yyyy.yy.RR.R.BB......W...............................BB..WBBBB.BBBBB.....TTTTTTTTTTTTTTTTTTT~~~~~~T', // 223
    '..................................RW....................uuuuuuuuu..uuuuu.yyyyyyy..yyy..WBB...WWWBBB........F...yyy.yyyy.yy.RRR..BB......W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 224
    '..................................RW....................uuuuuuuuuuuuuuuu..yyyyyyyyyyyy.WBB..WWWBBB.........WW...yyyyyyyyyy.RR...BB......W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 225
    '..................................RR...................uuuuuuuuuuuuuuuuuu..yyyyyyyyyyy.WW...WWBBB..........WW...yyyyyyyyyy.R....BBBBBBBBW...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 226
    '..................................RR...................uuuuuuuuuuuuuuuuuuu.yyyyyyyyyy....WWW..BB............WRR.yyyyyyyyyy.RR...BBBBBBBBW...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 227
    '..................................RR....................uuuuuuuu.uuuuuuuuuBB.yyyyyyy.......W................WRR..yyyyyyyyy.RR...........W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 228
    '..................................RR..................................u..BBB..yyyyy.........................WRRR..yyyyyyy..RR.W.........W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 229
    '..................................RR....................R.........R.........................................WRRR..........RRR.WWWWWWWWWWW...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 230
    'RRRRRRRRRRRRRRRRBBBBBBBBR.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR..BBBBR.R.RRRRRRRRRRRRRRRRRRRRRRRRFFFFR.RRRRR.W....WWWW.W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 231
    'RRRRRRRRRRRRRRRRBBBBBBBBR.R.RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRFRRR.RBBBBR.R..RRRRRRRRRRRRRRRRRRRRRRRR...RRR.RR...WWWWWWWW.W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 232
    'RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRBB.RRRRRRRRRRRRRRR.WWWWWWWWW.W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 233
    '...............................................................................................WWWW........BB.RR......RRRRRRR.WWWWWWWWW.W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 234
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAbbABBRRRA.....WWWWRRRWWWWWWWWWW.W...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 235
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBAWBBAbbbAAARRRA.WWWW..WRRRR.WW.BBWWWWWW...................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 236
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBWWBBAAbAAAARRRRRRRRRWWRRRRRWWW.BBB...W....................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 237
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWBBAAAAAAARRRRRRRRRWRRR.RRW...BBB........................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 238
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWAAAAAAAAAARRRW.RRRRWRRR.RRW...BBB.W......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 239
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbbAAAARRRW.RRRWWWRRRRRWW..BBB.W......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 240
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAAAARRAW.RRRWWWWWRW.BBB.BBB.W......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 241
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBAAAbAAARRW...WWWW.WWW.BBB.BBB.W......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 242
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBAbbbAAARRWWWWWWWWWWWWW....BBB.W......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 243
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbbbAARRRW...W.BBBB.W.....BBB.W......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 244
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRW.BBBBBBBB.......BBBWW...............WW.....................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 245
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRAAARRW.BBBBBBBB...........W...............WW.....................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 246
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRRRRRRRRWWWBBB..........WWW..WW......................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 247
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRRRRRRRRW.BBB......W...W..WWWW..BBBBB...............BB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 248
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAWW.BBB......W...WWW..WW..BBBBB..F.BBBB......BBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 249
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAWWBBB.....WW...W.....W..BBBB.yyy.BBBB.yyy..BBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 250
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAWWWBBBBBB..WW...WWBBB.W..BBBB.yyy.BBBB.yyy..BBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 251
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAWW.BBBBBBBB.W...W.BBBWW..BBBB.yyy..BBB.yy...BBB..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 252
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAW.BBBBBBBB.....W.BBB.W.....F.yyy............................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 253
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAAW.BBBBBBB..W...W.BBB.W......yyyyyyyyy.....yyyy..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 254
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAWWBBBBBBB.WW...W.BBBW......yyyyyyyyyy.....yyyyy.............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 255
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAAW.BBB.BBB.WW...W.BBBWWW....yyyyyyyyy....F..yy...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 256
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAWWWBBB......WW..W.BBBW.BBBB.y..............F.................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 257
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAWWWBBBBBBBBWW...W.BBBWWBBBByy................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 258
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWRWW.BBBBBBBB.WW..W.BBB.WBBBByy...BBB.yyyyyyyyyy...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 259
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRWWBBBBBBBB.WWWWW.BBB.WWBBByy...BBB....yyyyyyy...............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 260
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRW.BBB......WW.WW.BBB.WF...yy.FFBBB.....yyyyyy.F.............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 261
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRW.BBB......W..BBBBBB......yy....BB..........................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 262
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRWWBBB.....WW..BBBBBBW..yy.yy..yyyyyy.....BBB................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 263
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRRW.BBB.....WWWW..BBBBW..y..yy..yyy.......BBBB................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 264
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRRRW.BBBBBBBB.WBBBBBBBBW.........yyy..BB...BBBBWW..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 265
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRW.BBBBBBBB..BBBBBBBBW.........yyy.BBBB..BBBBBW..............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 266
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRW..BBBBBB...WWBBBBB.W....yy...yyy.BBBB..BBBBBWWW..W.........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 267
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRWWWWWWWWRWWWWWWRWWWWWW....W....y.............W..WWW.........................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 268
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAAAAAAAAAAARRRRRRRRRRRRRRRRRRRRRRRRRRR.WW.......BBBB......WWW.............................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 269
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWAAAAAAAAAAAAAAAAARRRA.RR.RWWWWFFFFFRWWWW.R...W........BBBB......................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 270
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA...........................................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 271
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA.yyy..yyyyyyyyyy..........WW...............................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 272
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA.yyyy.yyyyyyyyyy........WWW................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 273
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWAAAAAAAAAAAAAAAAAAAARRRA.yyyyyyyyyyyyyyy.........W.WWWW............................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 274
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWAAAAAAAAAAAAAAAAAAAAAARRRA.yyy..yyyyyyyyy............................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 275
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRF.yyyy.yyyyyyyy.............................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 276
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRF.yyyyyyyyyyyy..............................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 277
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA.yyyyyyy.yyyy..............................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 278
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA.yyyyyy...yy...............................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 279
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA.............F.............................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 280
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRA...........................................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 281
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA...........................................................................TTTTTTTTTTTTTTTTTTT~~~~~~T', // 282
  ],

  // Building names. `at` is any tile inside the building (x, y). Buildings
  // not listed here are still built from their B tiles, just unnamed.
  buildings: [
    { id: "cub", code: "CUB", name: "Central Utilities Building", at: [135, 21] },
    { id: "ah", code: "AH", name: "Alumni House & Visitor Center", at: [99, 24] },
    { id: "ser", code: "SER", name: "Service Building / Public Safety", at: [122, 27] },
    { id: "mpf", code: "MPF", name: "Multi-Purpose Facility", at: [46, 33] },
    { id: "hlc", code: "HLC", name: "Hoobler Living Center", at: [161, 37] },
    { id: "fc", code: "FC", name: "Hosford Football Center", at: [45, 39] },
    { id: "wlc", code: "WLC", name: "Weed Living Center", at: [142, 40] },
    { id: "flc", code: "FLC", name: "Frey Living Center", at: [167, 40] },
    { id: "olc", code: "OLC", name: "Ott Living Center", at: [137, 46] },
    { id: "dlc", code: "DLC", name: "DeVos Living Center", at: [170, 47] },
    { id: "rac", code: "RAC", name: "Ravine Center", at: [79, 49] },
    { id: "nlc", code: "NLC", name: "North C Living Center", at: [159, 51] },
    { id: "klc", code: "KLC", name: "Kleiner Commons", at: [151, 53] },
    { id: "plc", code: "PLC", name: "Pew Living Center", at: [172, 57] },
    { id: "jlc", code: "JLC", name: "Johnson Living Center", at: [147, 58] },
    { id: "hll", code: "HLL", name: "Hills Living Center", at: [166, 62] },
    { id: "kis", code: "KIS", name: "Kistler Living Center", at: [155, 65] },
    { id: "krp", code: "KRP", name: "Kirkpatrick Living Center", at: [176, 65] },
    { id: "sta", code: "STA", name: "Stafford Living Center", at: [188, 65] },
    { id: "cop", code: "COP/ROB", name: "Copeland Living Center / Robinson Living Center", at: [146, 71] },
    { id: "pkc", code: "PKC", name: "Pickard Living Center", at: [165, 71] },
    { id: "slc", code: "SLC", name: "Seidman Living Center", at: [175, 71] },
    { id: "fh", code: "FH/FHA/POOL/RC", name: "Fieldhouse / Fieldhouse Arena / Fieldhouse Natatorium / Recreation Center", at: [100, 72] },
    { id: "swn", code: "SWN", name: "Swanson Living Center", at: [186, 74] },
    { id: "ktb", code: "KTB", name: "Kelly Family Sports Center", at: [61, 80] },
    { id: "mak", code: "MAK/MAN", name: "Mackinac Hall / Manitou Hall", at: [133, 80] },
    { id: "hhlc", code: "HHLC", name: "Holton-Hooker Living Center", at: [149, 96] },
    { id: "khs", code: "KHS/LMP", name: "Kindschi Hall of Science / Marketplace", at: [111, 102] },
    { id: "mplc", code: "MPLC", name: "Maple Living Center", at: [166, 102] },
    { id: "com", code: "COM", name: "Commons", at: [137, 105] },
    { id: "oklc", code: "OKLC", name: "Oak Living Center", at: [158, 108] },
    { id: "pnlc", code: "PNLC", name: "Pine Living Center", at: [150, 109] },
    { id: "pad", code: "PAD/LTT/HRY/STU", name: "Padnos Hall of Science / Loutit Lecture Hall / Henry Hall / Lubbers Student Services Center", at: [125, 110] },
    { id: "cdc", code: "CDC", name: "Cook-DeWitt Center", at: [118, 135] },
    { id: "ash", code: "ASH", name: "Au Sable Hall", at: [152, 143] },
    { id: "lib", code: "LIB", name: "Mary Idema Pew Library", at: [98, 148] },
    { id: "kc", code: "KC", name: "Kirkhof Center", at: [109, 149] },
    { id: "jhz", code: "JHZ", name: "Zumberge Hall", at: [133, 149] },
    { id: "mmb", code: "MMB", name: "Meadows Maintenance Building", at: [43, 150] },
    { id: "cc", code: "CC", name: "Children's Enrichment Center", at: [57, 153] },
    { id: "lhh", code: "LHH", name: "Lake Huron Hall", at: [153, 158] },
    { id: "sh", code: "SH", name: "Seidman House", at: [148, 162] },
    { id: "lsh", code: "LSH", name: "Lake Superior Hall", at: [137, 163] },
    { id: "cr", code: "CR", name: "Calder Residence", at: [180, 165] },
    { id: "pac", code: "PAC/LAT", name: "Haas Center for Performing Arts / Louis Armstrong Theatre", at: [122, 168] },
    { id: "cac", code: "CAC", name: "Calder Art Center", at: [178, 171] },
    { id: "lmh", code: "LMH", name: "Lake Michigan Hall", at: [141, 173] },
    { id: "loh", code: "LOH", name: "Lake Ontario Hall", at: [150, 174] },
    { id: "lva1", code: "", name: "Laker Village Apartments", at: [63, 186] },
    { id: "lva2", code: "", name: "Laker Village Apartments", at: [68, 187] },
    { id: "lva3", code: "", name: "Laker Village Apartments", at: [75, 187] },
    { id: "lva4", code: "", name: "Laker Village Apartments", at: [65, 189] },
    { id: "nhh", code: "NHH/MUR/SUB", name: "Niemeyer Learning & Living Center / Murray Living Center / South Utilities Building", at: [154, 189] },
    { id: "lva5", code: "", name: "Laker Village Apartments", at: [59, 191] },
    { id: "lva6", code: "", name: "Laker Village Apartments", at: [81, 193] },
    { id: "lva7", code: "", name: "Laker Village Apartments", at: [83, 196] },
    { id: "con", code: "CON", name: "Blue Connection", at: [117, 198] },
    { id: "lva8", code: "", name: "Laker Village Apartments", at: [66, 200] },
    { id: "lva9", code: "", name: "Laker Village Apartments", at: [73, 200] },
    { id: "lva10", code: "", name: "Laker Village Apartments", at: [83, 201] },
    { id: "lva11", code: "", name: "Laker Village Apartments", at: [88, 201] },
    { id: "lva12", code: "", name: "Laker Village Apartments", at: [76, 202] },
    { id: "lva13", code: "", name: "Laker Village Apartments", at: [55, 205] },
    { id: "lva14", code: "", name: "Laker Village Apartments", at: [83, 205] },
    { id: "lva15", code: "", name: "Laker Village Apartments", at: [72, 206] },
    { id: "lva16", code: "", name: "Laker Village Apartments", at: [90, 206] },
    { id: "lva17", code: "", name: "Laker Village Apartments", at: [82, 208] },
    { id: "lva18", code: "", name: "Laker Village Apartments", at: [55, 210] },
    { id: "lva19", code: "", name: "Laker Village Apartments", at: [76, 210] },
    { id: "lva20", code: "", name: "Laker Village Apartments", at: [100, 210] },
    { id: "lva21", code: "", name: "Laker Village Apartments", at: [96, 212] },
    { id: "vlc", code: "VLC", name: "VanSteeland Living Center", at: [129, 214] },
    { id: "lva22", code: "", name: "Laker Village Apartments", at: [82, 217] },
    { id: "lva23", code: "", name: "Laker Village Apartments", at: [55, 218] },
    { id: "lva24", code: "", name: "Laker Village Apartments", at: [89, 218] },
    { id: "lva25", code: "", name: "Laker Village Apartments", at: [95, 218] },
    { id: "lva26", code: "", name: "Laker Village Apartments", at: [101, 220] },
    { id: "lva27", code: "", name: "Laker Village Apartments", at: [88, 224] },
    { id: "lva28", code: "", name: "Laker Village Apartments", at: [74, 228] },
    { id: "lva29", code: "", name: "Laker Village Apartments", at: [82, 231] },
    { id: "uhc", code: "UHC", name: "Campus Health Center", at: [95, 236] },
    { id: "sae1", code: "", name: "South Apartments", at: [129, 236] },
    { id: "ags", code: "AGS", name: "Art Gallery Support Building", at: [97, 241] },
    { id: "sae2", code: "", name: "South Apartments", at: [125, 241] },
    { id: "sac", code: "SAC", name: "South Apartment C", at: [118, 244] },
    { id: "gva1", code: "", name: "Grand Valley Apartments", at: [136, 248] },
    { id: "gva2", code: "", name: "Grand Valley Apartments", at: [156, 248] },
    { id: "gva3", code: "", name: "Grand Valley Apartments", at: [145, 249] },
    { id: "sad", code: "SAD", name: "South Apartment D", at: [129, 251] },
    { id: "gva4", code: "", name: "Grand Valley Apartments", at: [143, 259] },
    { id: "gva5", code: "", name: "Grand Valley Apartments", at: [153, 263] },
    { id: "gva6", code: "", name: "Grand Valley Apartments", at: [147, 265] },
    { id: "gva7", code: "", name: "Grand Valley Apartments", at: [146, 269] },
  ],
};
